version: 2.1
orbs:
  node: circleci/node@5.1.0
workflows:
    example-workflow:
      jobs:
        - node/run:
            pkg-manager: npm 
            resource_class: large 
            npm-run: lint 
            version: '14.21.3' 